version: "3.8"

services:
  api:
    build: .
    container_name: aqi_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mlflow
      - prefect-server

  mlflow:
    image: python:3.11-slim
    container_name: aqi_mlflow
    working_dir: /mlflow
    command: >
      bash -c "
      pip install mlflow &&
      mkdir -p /mlflow/mlruns &&
      mlflow server
        --backend-store-uri sqlite:///mlflow.db
        --default-artifact-root /mlflow/mlruns
        --host 0.0.0.0
        --port 5000
      "
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow

  prefect-server:
    image: prefecthq/prefect:2-latest
    container_name: prefect_server
    command: ["prefect", "server", "start"]
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - prefect_data:/root/.prefect
    depends_on:
      - mlflow

  prefect-agent:
    image: prefecthq/prefect:2-latest
    container_name: prefect_agent
    command: ["prefect", "agent", "start", "-q", "default"]
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - .:/app
    depends_on:
      - prefect-server

volumes:
  prefect_data: